// Sovereign Engine
// Copyright (c) 2025 opticfluorine
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Generic;
using System.Threading;
using Sovereign.EngineCore.Components.Indexers;
using Sovereign.EngineUtil.Attributes;

namespace Sovereign.EngineCore.Systems.Players;

/// <summary>
///     Lua scripting library for looking up online players by name.
/// </summary>
/// <remarks>
///     Exact lookups (<see cref="FindByName" />) are case-insensitive and O(1).
///     Fuzzy lookups (<see cref="FindByFuzzyName" />) scan all online player
///     names with a Damerau-Levenshtein similarity scoring and return the
///     top-N matches. Scripts may run on separate Lua hosts and call into
///     this library concurrently; all public methods are serialized through
///     <see cref="syncRoot" /> so that the reusable internal scratch and the
///     underlying <see cref="PlayerNameComponentIndexer" /> fuzzy state are
///     not accessed concurrently. <see cref="FindByFuzzyName" /> returns a
///     freshly allocated list per call so that the autogenerated Lua
///     marshaller, which reads the returned list after this method returns
///     (outside the lock), is never racing with a subsequent concurrent call.
/// </remarks>
[ScriptableLibrary("Players")]
public sealed class PlayersScripting(PlayerNameComponentIndexer playerNameIndex)
{
    /// <summary>
    ///     Server-side cap on the number of fuzzy results returned per call.
    /// </summary>
    private const int MaxFuzzyResults = 64;

    /// <summary>
    ///     Lock object serializing all public method calls so that the
    ///     reusable scratch and the shared indexer fuzzy state are not
    ///     accessed concurrently across Lua hosts.
    /// </summary>
    private readonly Lock syncRoot = new();

    /// <summary>
    ///     Reusable scratch list for fuzzy (name, score) tuples. Cleared and
    ///     refilled on each <see cref="FindByFuzzyName" /> call. Only ever
    ///     touched while holding <see cref="syncRoot" />.
    /// </summary>
    private readonly List<(string Name, float Score)> fuzzyScratch = new();

    /// <summary>
    ///     Looks up an online player entity by name (case-insensitive, O(1)).
    /// </summary>
    /// <param name="name">Player name.</param>
    /// <returns>Player entity ID, or 0 if no online player has the given name.</returns>
    [ScriptableFunction("FindByName")]
    public ulong FindByName(string name)
    {
        lock (syncRoot)
        {
            return playerNameIndex.TryGetPlayerByName(name, out var id) ? id : 0UL;
        }
    }

    /// <summary>
    ///     Performs a fuzzy lookup of online players by name, returning the
    ///     top-N matches ordered by descending similarity score (ties broken
    ///     alphabetically).
    /// </summary>
    /// <param name="name">Query name.</param>
    /// <param name="maxResults">
    ///     Maximum number of results. Clamped to [1, 64] server-side.
    /// </param>
    /// <returns>
    ///     Up to <paramref name="maxResults" /> matches, best-first, in a
    ///     freshly allocated list owned by the caller. The list is safe to
    ///     read after this method returns because it is not retained
    ///     internally.
    /// </returns>
    [ScriptableFunction("FindByFuzzyName")]
    public List<PlayerNameMatch> FindByFuzzyName(string name, int maxResults)
    {
        if (maxResults < 1) maxResults = 1;
        if (maxResults > MaxFuzzyResults) maxResults = MaxFuzzyResults;

        lock (syncRoot)
        {
            fuzzyScratch.Clear();
            playerNameIndex.AppendFuzzyMatches(name, maxResults, fuzzyScratch);

            var results = new List<PlayerNameMatch>(fuzzyScratch.Count);
            foreach (var (n, s) in fuzzyScratch)
            {
                if (!playerNameIndex.TryGetPlayerByName(n, out var eid)) continue;
                results.Add(new PlayerNameMatch
                {
                    EntityId = eid,
                    Name = n,
                    Score = s
                });
            }

            return results;
        }
    }
}
