# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main", "dependabot/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: opticfluorine/sovereign-resources
          path: resources
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Setup glslc
        run: curl https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/418/20230531-104531/install.tgz -o install.tgz && tar -xzf install.tgz && sudo cp -r install/bin/* /usr/local/bin && sudo cp -r install/include/* /usr/local/include && sudo cp -r install/lib/* /usr/local/lib && sudo ldconfig
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build --no-restore
        working-directory: src
      - name: Test
        run: dotnet test --no-restore
        working-directory: src
      - name: Publish (Linux x64)
        run: dotnet publish -r linux-x64 -c Release --sc true
        working-directory: src
      - name: Publish (Windows x64)
        run: dotnet publish -r win-x64 -c Release --sc true
        working-directory: src
      - name: Archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts
          pushd Client/SovereignClient/bin/Release/net8.0
          pushd linux-x64
          cp -r $GITHUB_WORKSPACE/resources/Data publish/
          tar zcf $GITHUB_WORKSPACE/artifacts/SovereignClient-$GITHUB_REF_NAME-linux-x64.tar.gz --transform s/publish/SovereignClient-$GITHUB_REF_NAME/ publish/
          popd
          pushd win-x64/publish
          cp -r $GITHUB_WORKSPACE/resources/Data .
          zip -r $GITHUB_WORKSPACE/artifacts/SovereignClient-$GITHUB_REF_NAME-win-x64.zip *
          popd
          popd
          pushd Server/SovereignServer/bin/Release/net8.0
          pushd linux-x64
          tar zcf $GITHUB_WORKSPACE/artifacts/SovereignServer-$GITHUB_REF_NAME-linux-x64.tar.gz --transform s/publish/SovereignServer-$GITHUB_REF_NAME/ publish/
          popd
          pushd win-x64/publish
          zip -r $GITHUB_WORKSPACE/artifacts/SovereignServer-$GITHUB_REF_NAME-win-x64.zip *
          popd
          popd
        working-directory: src
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          files: artifacts/*
