# This is a basic workflow to help you get started with Actions

name: Post-Release

# Controls when the workflow will run
on:
  # Run whenever a new release is published.
  release:
    types: [ published ]
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger Documentation Site Publish
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOC_PUB_EVENT_PAT }}
          repository: opticfluorine/sovereign-site-docs
          event-type: sovereign_release
